spring:
  application:
    name: eureka
server:
  host: http://localhost
  port: 9091
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: ${server.host}:${server.port}/eureka,http://localhost:9090/eureka
  instance:
    prefer-ip-address: true