spring:
  application:
    # 服务名称 - 服务之间使用名称进行通讯
    name: goods
tx-lcn:
  client:
    manager-address: 127.0.0.1:8070   #指定TM地址
  ribbon:
    loadbalancer:
      dtx:
        enabled: true                    #开启启动LCN负载均衡策略

